[File]
RunDir = "../RUNS"
RunName = "Testing"

[Teensy]
Port = "COM4"

PIDRelay = false
GeneralRelay = false

PID1Enable = false
PID1TempSetpoint = -18
PID1CurrentSetpoint = 5
PID1TKp = -3e3
PID1TTi = 50e3
PID1TTd = 0
PID1AKp = 200
PID1ATi = 100
PID1ATd = 0

PID2Enable = false
PID2TempSetpoint = 0
PID2CurrentSetpoint = 3
PID2TKp = -2000
PID2TTi = 100
PID2TTd = 0
PID2AKp = 200
PID2ATi = 100
PID2ATd = 0

[CAEN]
# DT5730B or DT5740D
Model = "DT5740D"
# 0 = not allowed
RecordLength = 180
MaxEventsPerRead = 512
PostBufferPorcentage = 50
OverlappingRejection = 0
TRGINasGate = false
# 0 = disabled, 1 = ACQ only, 2 = ext mode only, 3 = both
ExternalTrigger = 1
SoftwareTrigger = 1
# 0 = rising edge, 1 = falling edge
Polarity = 1

# Individual Channel settings
[CAEN.group0]
Enabled = 1
# Group or channel number
Number = 0
# Group offset
Offset = 0x8000
# Individual corrections to offset
Corrections = [0, 0, 0, 0, 0, 0, 0, 0]

Range = 1
Threshold = 2075


# [CAEN.ch1]
# Enabled = 0
# Channel = 1
# Offset = 0x8000
# # 0 = rising edge, 1 = falling edge
# Polarity = 1
# Range = 1
# Threshold = 2075