[File]
RunDir = "C:\\Users\\SBC\\Documents\\SIPM-Testing-Software"
RunName = "RUNS"

[Teensy]
Port = "COM3"

PIDEnable = false
PeltierTempSetpoint = -90
NTempSetpoint = -100

PeltierTKp = -3e3
PeltierTTi = 50e3
PeltierTTd = 0

NTKp = -1e3
NTTi = 10e3
NTTd = 0

[CAEN]
# DT5730B or DT5740D
Model = "DT5740D"
Port = 0
# 0 = not allowed
RecordLength = 180
MaxEventsPerRead = 500
PostBufferPorcentage = 50
OverlappingRejection = false
TRGINasGate = false
# 0 = disabled, 1 = ACQ only, 2 = ext mode only, 3 = both
ExternalTrigger = 1
SoftwareTrigger = 1
# 0 = rising edge, 1 = falling edge
Polarity = 1
# 0 = NIM, 1 = TTL
IOLevel = 0

# Individual Channel settings
# The number after group represents
# the # of the group (or channel)
[CAEN.group0]
Enabled = 1
# Trigger Enable Mask
TrgMask = 7
# Acquisition Enable Mask
AcqMask = 7
# Group offset
Offset = 0x8000
# Individual corrections to offset
Corrections = [5, 0, 6, 0, 0, 0, 0, 0]

Range = 0
Threshold = 2103

# [CAEN.group1]
# Enabled = 0
# Offset = 0x8000
# Corrections = [0, 0, 0, 0, 0, 0, 0, 0]
# Range = 1
# Threshold = 2075
